scrape_configs:

#### auto discovery config ####
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 9090
    relabel_configs:
      - source_labels: [__meta_docker_container_label_monitoring_job]
        regex: .+
        action: keep
      - regex: __meta_docker_container_label_monitoring_(.+)
        action: labelmap
        replacement: $1%