version: '3.9'

serices: 
  
  grafana:
    container_name: grafana
    image: grafana:latest
    ports:
      - 3000:3000
    networks:
      - devops_course
    environment:
      - GF_SECURITY_ADMIN_USER=devops
      - GF_SECURITY_ADMIN_PASSWORD=devops  
    volumes:
      - ./grafana-storage:/var/lib/grafana

  prometheus:
    container_name: prometheus
    image: prometheus:latest
    ports: 
      - '127.0.0.1:9090:9090'
    networks:
      - devops_course
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./prometheus-storage:/prometheus
    labels:
      - monitoring-job=prometheus

networks:
  devops_course:
    external: true